In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)  # Output: [[1 2] [3 4] [5 6] [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
import numpy as np

arr = np.array ([1, 2, 3, 4, 5, 6, 7])
newarr = np.array_split(arr, 3)
print(newarr)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [8]:
my_dict = {"name": "Mike", "age": 25, "city": "NYC"}

for key, value in my_dict.items():
    print(key, value)

name Mike
age 25
city NYC


In [9]:
import numpy as np

scores = [4.8, 3.5, 4.1]
# ascending is default:
print(np.argsort(scores))

# descending:
print(np.argsort(scores)[::-1])

np.set_printoptions(precision=4, suppress=True)
arr = np.array([13434343.34344343, 2434343.4343, 34343.434, 44343.43434343, 534343434.3434343])
print(arr)

[1 2 0]
[0 2 1]
[1.3434e+07 2.4343e+06 3.4343e+04 4.4343e+04 5.3434e+08]
